#!/bin/bash

exec 2>&1

#
# Start Grafana
#
exec grafana-server --homepath={{pkg.path}} \
    --config={{pkg.svc_config_path}}/grafana.ini \
    --pidfile={{pkg.svc_var_path}}/grafana-server.pid \
    cfg:default.paths.data={{pkg.svc_var_path}} \
    cfg:default.paths.logs={{pkg.svc_var_path}} \
    cfg:default.paths.plugins={{pkg.svc_var_path}}/plugins \
    cfg:default.paths.provisioning={{pkg.svc_var_path}}/provisioning
