pipeline {

    agent any

    environment {
        ARM_CLIENT_ID       = credentials('arm-client-id')
        ARM_CLIENT_SECRET   = credentials('arm-client-secret')
        ARM_TENANT_ID       = credentials('arm-tenant-id')
        ARM_SUBSCRIPTION_ID = credentials('arm-subscription-id')
    }

    stages {
        stage('Install Packer') {
            steps {
                sh "sudo hab pkg install -b core/packer"
            }
        }
        stage('CentOS Validate') {
            steps {
                dir("packer") {
                    sh "packer validate -var-file centos-variables.json azure-linux-machine-image.json"
                }
            }
        }
        stage('CentOS Build') {
            when {
                branch 'master'
            }
            steps {
                dir("packer") {
                    sh "packer build -var-file centos-variables.json azure-linux-machine-image.json"
                }
            }
        }
    }
}
