pipeline {

    agent any

    environment {
        ARM_CLIENT_ID       = credentials('arm-client-id')
        ARM_CLIENT_SECRET   = credentials('arm-client-secret')
        ARM_TENANT_ID       = credentials('arm-tenant-id')
        ARM_SUBSCRIPTION_ID = credentials('arm-subscription-id')
    }

    stages {
        stage('CentOS Build') {
            steps {
                dir("packer") {
                    sh "packer build -var-file=centos-variables.json azure-linux-machine-image.json"
                }
            }
        }
    }
}
