pipeline {

    agent any

    environment {
        ARM_CLIENT_ID       = credentials('arm-client-id')
        ARM_CLIENT_SECRET   = credentials('arm-client-secret')
        ARM_TENANT_ID       = credentials('arm-tenant-id')
        ARM_SUBSCRIPTION_ID = credentials('arm-subscription-id')
        VAULT_TOKEN         = credentials('vault-token')
    }

    stages {
        stage('Terraform Initialization') {
            steps {
                dir("terraform/example-3") {
                    sh "terraform init"
                }
            }
        }
        stage('Terraform Validation') {
            steps {
                dir("terraform/example-3") {
                    sh "terraform validate"
                }
            }
        }
        stage('Terraform Apply') {
            steps {
                dir("terraform/example-3") {
                    sh "terraform apply -var habitat_origin=${env.HAB_ORIGIN} -auto-approve"
                }
            }
        }
        stage('Terraform Output') {
            steps {
                dir("terraform/example-3") {
                    sh "terraform output"
                }
            }
        }
    }
}
