pipeline {

    agent any

    environment {
        ARM_CLIENT_ID       = credentials('arm-client-id')
        ARM_CLIENT_SECRET   = credentials('arm-client-secret')
        ARM_TENANT_ID       = credentials('arm-tenant-id')
        ARM_SUBSCRIPTION_ID = credentials('arm-subscription-id')
    }

    stages {
        stage('Install Terraform') {
            steps {
                sh "sudo hab pkg install -b liftoff-modern-application-delivery/terraform"
            }
        }
        stage('Terraform Initialization') {
            steps {
                dir("examples/example-1-server-provisioning/terraform-pipeline") {
                    sh "terraform init"
                }
            }
        }
        stage('Terraform Validation') {
            steps {
                dir("examples/example-1-server-provisioning/terraform-pipeline") {
                    sh "terraform validate"
                }
            }
        }
        stage('Terraform Apply') {
            when {
                branch 'master'
            }
            steps {
                dir("examples/example-1-server-provisioning/terraform-pipeline") {
                    sh "terraform apply -auto-approve"
                }
            }
        }
    }
}
