# The port + protocol that the Grafana UI listens on
http_port = 8000
protocol  = "http"
cert_file = "" # path to cert file
cert_key  = "" # path to key

# LDAP config
ldap_enabled         = "false"
ldap_host            = ""
ldap_bind_dn         = ""
ldap_bind_password   = ""
ldap_search_base_dns = ""
ldap_admin_group     = ""
ldap_editor_group    = ""
ldap_viewer_group    = "*"

# Default credentials for Grafana UI
admin_user     = "admin"
admin_password = "password"

